inc:
  # Blog Information
  title:        "Blog"
  subtitle:     "Noticias y pistas del Máster en Innovación en Periodismo"
  cover_image:  blog-cover.jpg
  logo:         logo.jpg

  # Company information
  company:      Máster en Innovación en Periodismo
  url:          http://mip.umh.es
  facebook:     mipumh
  twitter:      mipumh
  gplus:        '103906596485859350077'
  
  # Product Information
  product_link: http://mip.umh.es/?utm_source=blog&utm_campaign=blog
  tagline:      "Idea, diseña, emprende"
  google_font: 'Droid+Sans:400,700'

# Analytics     
  analytics:
    google: true
 
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: http://mip.umh.es/blog

collections:
  conferencias:
    output: true
    permalink: /:collection/:title

# Build settings
markdown: kramdown

plugins: [jekyll-paginate]
permalink:     pretty
paginate_path: 'page:num'
paginate: 10
