backend:
  name: git-gateway
  branch: redesign

publish_mode: editorial_workflow

media_folder: "images/001"
public_folder: "{{site.baseurl}}/images/001"

locale: "es"

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: "posts"
    label: "Artículos"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sortable_fields: ["title", "date"]
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "article" }
      - { label: "Published", name: "published", widget: "hidden", default: false }
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Subtítulo", name: "subtitle", widget: "string", required: false }
      - label: "Autor"
        name: "author"
        widget: "select"
        options:
          - { label: "Miguel Carvajal", value: "carvajal" }
          - { label: "Jose A. García Avilés", value: "garcia-aviles" }
          - { label: "Félix Arias", value: "arias" }
          - { label: "Alicia de Lara", value: "de-lara" }
          - { label: "Cristian R. Marín", value: "marin" }
          - { label: "Alba García Ortega", value: "garcia-ortega" }
          - { label: "Chema Valero", value: "valero" }
          - { label: "Dámaso Mondéjar", value: "mondejar" }
          - { label: "José Luis Rojas", value: "rojas" }
          - { label: "Itziar Martínez", value: "martinez" }
      - label: "Sección"
        name: "categories"
        widget: "select"
        options:
          - { label: "Narrativas", value: "narrativas" }
          - { label: "Industria", value: "industria" }
          - { label: "Tecnología", value: "tecnologia" }
          - { label: "Redacción", value: "redaccion" }
          - { label: "Audiencias", value: "audiencias" }
          - { label: "Innovadores", value: "innovadores" }
          - { label: "El Máster", value: "el-master" }
        default: "narrativas"
      - label: "Etiquetas"
        name: "tags"
        widget: "list"
        required: false
      - label: "Imagen de portada"
        name: "image"
        widget: "image"
        required: false
        media_folder: "/images/covers"
      - label: "Destacado"
        name: "featured"
        widget: "boolean"
        default: false
        required: false
      - { label: "Borrador", name: "draft", widget: "boolean", default: false, required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }
