#!/usr/bin/env python3
"""
Fetch top pages from GA4 and write _data/popular.yml for the blog sidebar.

Usage:
    python3 scripts/update_popular.py

Requires:
    - scripts/ga4-credentials.json  (Service Account key)
    - pip install google-analytics-data pyyaml

The script queries the GA4 Data API for the most-viewed blog posts
in the last 90 days and writes the top 10 to _data/popular.yml.
"""

import os
import re
import yaml
from datetime import datetime, timedelta
from google.analytics.data_v1beta import BetaAnalyticsDataClient
from google.analytics.data_v1beta.types import (
    DateRange,
    Dimension,
    Metric,
    RunReportRequest,
    FilterExpression,
    Filter,
)

# ── Config ────────────────────────────────────────────────────────────────
PROPERTY_ID = "386593196"
CREDENTIALS_PATH = os.path.join(os.path.dirname(__file__), "ga4-credentials.json")
OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "_data", "popular.yml")
TOP_N = 10
DAYS = 90

# Blog post URL pattern: /blog/YYYY/MM/DD/slug/
POST_URL_RE = re.compile(r"^/blog/(\d{4})/(\d{2})/(\d{2})/[^/]+/?$")


def fetch_top_posts():
    """Query GA4 for the most viewed blog post pages."""
    os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = CREDENTIALS_PATH

    client = BetaAnalyticsDataClient()

    request = RunReportRequest(
        property=f"properties/{PROPERTY_ID}",
        date_ranges=[DateRange(start_date=f"{DAYS}daysAgo", end_date="today")],
        dimensions=[Dimension(name="pagePath"), Dimension(name="pageTitle")],
        metrics=[Metric(name="screenPageViews")],
        dimension_filter=FilterExpression(
            filter=Filter(
                field_name="pagePath",
                string_filter=Filter.StringFilter(
                    match_type=Filter.StringFilter.MatchType.BEGINS_WITH,
                    value="/blog/20",
                ),
            )
        ),
        order_bys=[
            {
                "metric": {"metric_name": "screenPageViews"},
                "desc": True,
            }
        ],
        limit=100,
    )

    response = client.run_report(request)

    results = []
    seen_paths = set()

    for row in response.rows:
        path = row.dimension_values[0].value.rstrip("/")
        title = row.dimension_values[1].value
        views = int(row.metric_values[0].value)

        # Only blog post URLs (not section pages, tag pages, etc.)
        m = POST_URL_RE.match(path + "/")
        if not m:
            continue

        # Only posts published in the last DAYS days
        pub_date = datetime(int(m.group(1)), int(m.group(2)), int(m.group(3)))
        if pub_date < datetime.now() - timedelta(days=DAYS):
            continue

        # Deduplicate (with/without trailing slash)
        if path in seen_paths:
            continue
        seen_paths.add(path)

        # Clean title: remove " | Site Title" suffix
        title = re.sub(r"\s*[|–—].*$", "", title).strip()
        if not title:
            continue

        results.append({"title": title, "url": path + "/", "views": views})

        if len(results) >= TOP_N:
            break

    return results


def write_yaml(posts):
    """Write the popular posts list to _data/popular.yml."""
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by scripts/update_popular.py\n")
        f.write(f"# Top {TOP_N} posts by pageviews (last {DAYS} days)\n\n")
        yaml.dump(posts, f, allow_unicode=True, default_flow_style=False, sort_keys=False)

    print(f"Wrote {len(posts)} popular posts to {OUTPUT_PATH}")


if __name__ == "__main__":
    posts = fetch_top_posts()
    if posts:
        write_yaml(posts)
        for i, p in enumerate(posts, 1):
            print(f"  {i}. [{p['views']:,} views] {p['title']}")
    else:
        print("No data returned. Check GA4 property access and credentials.")
